### ISSUE TITLE
Now how to avoid this? extended image

### ISSUE THREAD

**Issue by babulpatel1309** [ductranit/flutter_universal_image#1]
I'm facing an issue related to flutter version.

If i use your library on stable channel then i face this error

`../../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-1.3.1-dev/lib/src/extended_image.dart:785:32: Error: Method not found: 'MediaQuery.maybeOf'.
    _invertColors = MediaQuery.maybeOf(context)?.invertColors ??`

And if i force app to use 1.3.0 (Stable version of extended image) then facing below error.

![Screenshot 2020-11-25 at 6 50 04 PM](https://user-images.githubusercontent.com/7448808/100232992-21beb400-2f4f-11eb-9155-fce6179d04e2.png)

Can you please guide me how can i resolve the version error?

### Does your library supports to cache the SVGs? @ductranit

**Comment by ductranit** [comment]
hi @babulpatel1309, my library only works on flutter master channel. If you can accept this, then switch to master by `flutter channel master` and remove the override, it should work
For the svg, I used [flutter_svg](https://pub.dev/packages/flutter_svg) and that library seems doesn't have cache.
