### ISSUE TITLE
Cache for Svg Image

### ISSUE THREAD

**Issue by rdcoder33** [ductranit/flutter_universal_image#2]
Cache didn't work SVG image. Using a network SVG image but get Load every time from the network rather than from cache.

```
child: UniversalImage(
                                                          bookData[
                                                                  'SvgCover'] ,
                                                          fit: BoxFit.fill,
                                                          
                                                          enableMemoryCache:
                                                              true,
                                                          cache: true,
                                                          placeholder: SizedBox(
                                                            width: 50,
                                                            height: 50,
                                                            child: Center(
                                                              child:
                                                                  CircularProgressIndicator(),
                                                            ),
                                                          ),
                                                        ),
```

**Comment by ductranit** [comment]
Sorry for late, please update universal_image to 0.1.1.
I just add `cacheColorFilter` property. 
[flutter_svg](https://github.com/dnfield/flutter_svg) just updates the color filter cache recently, and this library depends on it.
You can check it [here](https://github.com/dnfield/flutter_svg/blob/master/lib/svg.dart#L665)
From the doc:
```
Whether to cache the picture with the [colorFilter] applied or not.  
This value should be set to true if the same SVG will be rendered with  
multiple colors, but false if it will always (or almost always) be  
rendered with the same [colorFilter].  
If [Svg.cacheColorFilterOverride] is not null, it will override this value  
for all widgets, regardless of what is specified for an individual widget.
This defaults to false and must not be null.
```

**Comment by rdcoder33** [comment]
Thanks for getting back at this. But the issue wasn't about SVG colors. In my case, the SVG will always render with the same color.

> I am using the latest version of flutter_universal_image


My issue is that SVG isn't getting cached. So if I open the app with the internet SVG will load but after an initial load if I open the app again without internet the svgs don't load implying svgs are not saved in cache but are getting fetched from the network every time.

In the case of png/jpg images did get load without internet through cache, it's just the SVGs that are not working.
I request you to look for that, all I need is to save SVG images of my app in Cache.

Best Wishes.

**Comment by ductranit** [comment]
hi @rdcoder33 I got your point, but this feature isn't supported by `flutter_svg`, and `flutter_universal_image` is just a wrapper of `flutter_svg`, it can only do what `flutter_svg` can do, I have no idea to support you that at the moment.
If you need svg cache feature, please fire a request on [flutter_svg](https://github.com/dnfield/flutter_svg/issues), or you can find a way to that, don't hesitate to create a pull request for them & add a comment here, I think it's something on [picture_provider](https://github.com/dnfield/flutter_svg/blob/master/lib/src/picture_provider.dart#L487)
Or you can try another lib for svg https://pub.dev/packages/svg_cached_network_image
Thanks!
